-- 创建财务报表、财务指标及业绩披露数据表。
-- 字段说明采用对应 Tushare 接口口径；数值按来源单位入库，日期以 DATE 存储。
-- 将本迁移会话的时区设为 UTC。
SET time_zone = '+00:00';

CREATE TABLE `tushare_pro__income` (
    `ts_code` VARCHAR(64) NOT NULL COMMENT 'TS代码',
    `ann_date` DATE NOT NULL COMMENT '公告日期',
    `f_ann_date` DATE NULL COMMENT '实际公告日期',
    `end_date` DATE NOT NULL COMMENT '报告期',
    `report_type` VARCHAR(64) NOT NULL COMMENT '财务报告类型（合并、单季、调整前后等来源分类）',
    `comp_type` VARCHAR(64) NULL COMMENT '公司类型(1一般工商业2银行3保险4证券7多元金融)',
    `end_type` VARCHAR(64) NULL COMMENT '报告期类型',
    `basic_eps` DECIMAL(38,18) NULL COMMENT '基本每股收益',
    `diluted_eps` DECIMAL(38,18) NULL COMMENT '稀释每股收益',
    `total_revenue` DECIMAL(38,18) NULL COMMENT '营业总收入',
    `revenue` DECIMAL(38,18) NULL COMMENT '营业收入',
    `int_income` DECIMAL(38,18) NULL COMMENT '利息收入',
    `prem_earned` DECIMAL(38,18) NULL COMMENT '已赚保费',
    `comm_income` DECIMAL(38,18) NULL COMMENT '手续费及佣金收入',
    `n_commis_income` DECIMAL(38,18) NULL COMMENT '手续费及佣金净收入',
    `n_oth_income` DECIMAL(38,18) NULL COMMENT '其他经营净收益',
    `n_oth_b_income` DECIMAL(38,18) NULL COMMENT '加:其他业务净收益',
    `prem_income` DECIMAL(38,18) NULL COMMENT '保险业务收入',
    `out_prem` DECIMAL(38,18) NULL COMMENT '减:分出保费',
    `une_prem_reser` DECIMAL(38,18) NULL COMMENT '提取未到期责任准备金',
    `reins_income` DECIMAL(38,18) NULL COMMENT '其中:分保费收入',
    `n_sec_tb_income` DECIMAL(38,18) NULL COMMENT '代理买卖证券业务净收入',
    `n_sec_uw_income` DECIMAL(38,18) NULL COMMENT '证券承销业务净收入',
    `n_asset_mg_income` DECIMAL(38,18) NULL COMMENT '受托客户资产管理业务净收入',
    `oth_b_income` DECIMAL(38,18) NULL COMMENT '其他业务收入',
    `fv_value_chg_gain` DECIMAL(38,18) NULL COMMENT '加:公允价值变动净收益',
    `invest_income` DECIMAL(38,18) NULL COMMENT '加:投资净收益',
    `ass_invest_income` DECIMAL(38,18) NULL COMMENT '其中:对联营企业和合营企业的投资收益',
    `forex_gain` DECIMAL(38,18) NULL COMMENT '加:汇兑净收益',
    `total_cogs` DECIMAL(38,18) NULL COMMENT '营业总成本',
    `oper_cost` DECIMAL(38,18) NULL COMMENT '减:营业成本',
    `int_exp` DECIMAL(38,18) NULL COMMENT '减:利息支出',
    `comm_exp` DECIMAL(38,18) NULL COMMENT '减:手续费及佣金支出',
    `biz_tax_surchg` DECIMAL(38,18) NULL COMMENT '减:营业税金及附加',
    `sell_exp` DECIMAL(38,18) NULL COMMENT '减:销售费用',
    `admin_exp` DECIMAL(38,18) NULL COMMENT '减:管理费用',
    `fin_exp` DECIMAL(38,18) NULL COMMENT '减:财务费用',
    `assets_impair_loss` DECIMAL(38,18) NULL COMMENT '减:资产减值损失',
    `prem_refund` DECIMAL(38,18) NULL COMMENT '退保金',
    `compens_payout` DECIMAL(38,18) NULL COMMENT '赔付总支出',
    `reser_insur_liab` DECIMAL(38,18) NULL COMMENT '提取保险责任准备金',
    `div_payt` DECIMAL(38,18) NULL COMMENT '保户红利支出',
    `reins_exp` DECIMAL(38,18) NULL COMMENT '分保费用',
    `oper_exp` DECIMAL(38,18) NULL COMMENT '营业支出',
    `compens_payout_refu` DECIMAL(38,18) NULL COMMENT '减:摊回赔付支出',
    `insur_reser_refu` DECIMAL(38,18) NULL COMMENT '减:摊回保险责任准备金',
    `reins_cost_refund` DECIMAL(38,18) NULL COMMENT '减:摊回分保费用',
    `other_bus_cost` DECIMAL(38,18) NULL COMMENT '其他业务成本',
    `operate_profit` DECIMAL(38,18) NULL COMMENT '营业利润',
    `non_oper_income` DECIMAL(38,18) NULL COMMENT '加:营业外收入',
    `non_oper_exp` DECIMAL(38,18) NULL COMMENT '减:营业外支出',
    `nca_disploss` DECIMAL(38,18) NULL COMMENT '其中:减:非流动资产处置净损失',
    `total_profit` DECIMAL(38,18) NULL COMMENT '利润总额',
    `income_tax` DECIMAL(38,18) NULL COMMENT '所得税费用',
    `n_income` DECIMAL(38,18) NULL COMMENT '净利润(含少数股东损益)',
    `n_income_attr_p` DECIMAL(38,18) NULL COMMENT '净利润(不含少数股东损益)',
    `minority_gain` DECIMAL(38,18) NULL COMMENT '少数股东损益',
    `oth_compr_income` DECIMAL(38,18) NULL COMMENT '其他综合收益',
    `t_compr_income` DECIMAL(38,18) NULL COMMENT '综合收益总额',
    `compr_inc_attr_p` DECIMAL(38,18) NULL COMMENT '归属于母公司(或股东)的综合收益总额',
    `compr_inc_attr_m_s` DECIMAL(38,18) NULL COMMENT '归属于少数股东的综合收益总额',
    `ebit` DECIMAL(38,18) NULL COMMENT '息税前利润',
    `ebitda` DECIMAL(38,18) NULL COMMENT '息税折旧摊销前利润',
    `insurance_exp` DECIMAL(38,18) NULL COMMENT '保险业务支出',
    `undist_profit` DECIMAL(38,18) NULL COMMENT '年初未分配利润',
    `distable_profit` DECIMAL(38,18) NULL COMMENT '可分配利润',
    `rd_exp` DECIMAL(38,18) NULL COMMENT '研发费用',
    `fin_exp_int_exp` DECIMAL(38,18) NULL COMMENT '财务费用:利息费用',
    `fin_exp_int_inc` DECIMAL(38,18) NULL COMMENT '财务费用:利息收入',
    `transfer_surplus_rese` DECIMAL(38,18) NULL COMMENT '盈余公积转入',
    `transfer_housing_imprest` DECIMAL(38,18) NULL COMMENT '住房周转金转入',
    `transfer_oth` DECIMAL(38,18) NULL COMMENT '其他转入',
    `adj_lossgain` DECIMAL(38,18) NULL COMMENT '调整以前年度损益',
    `withdra_legal_surplus` DECIMAL(38,18) NULL COMMENT '提取法定盈余公积',
    `withdra_legal_pubfund` DECIMAL(38,18) NULL COMMENT '提取法定公益金',
    `withdra_biz_devfund` DECIMAL(38,18) NULL COMMENT '提取企业发展基金',
    `withdra_rese_fund` DECIMAL(38,18) NULL COMMENT '提取储备基金',
    `withdra_oth_ersu` DECIMAL(38,18) NULL COMMENT '提取任意盈余公积金',
    `workers_welfare` DECIMAL(38,18) NULL COMMENT '职工奖金福利',
    `distr_profit_shrhder` DECIMAL(38,18) NULL COMMENT '可供股东分配的利润',
    `prfshare_payable_dvd` DECIMAL(38,18) NULL COMMENT '应付优先股股利',
    `comshare_payable_dvd` DECIMAL(38,18) NULL COMMENT '应付普通股股利',
    `capit_comstock_div` DECIMAL(38,18) NULL COMMENT '转作股本的普通股股利',
    `continued_net_profit` DECIMAL(38,18) NULL COMMENT '持续经营净利润',
    `update_flag` VARCHAR(64) NULL COMMENT '来源数据更新标识',
    `source_plugin` VARCHAR(64) NOT NULL COMMENT '来源插件标识',
    `source_api` VARCHAR(64) NOT NULL COMMENT '来源接口名称',
    `ingested_at` DATETIME(3) NOT NULL COMMENT '数据入库时间（UTC，毫秒精度）',
    -- 以来源业务键唯一标识记录，支持重复下载时更新同一条数据。
    PRIMARY KEY (`ts_code`, `end_date`, `report_type`, `ann_date`),
    -- 支持按公告日期查询。
    KEY `idx_income_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='利润表';

CREATE TABLE `tushare_pro__balancesheet` (
    `ts_code` VARCHAR(64) NOT NULL COMMENT 'TS股票代码',
    `ann_date` DATE NOT NULL COMMENT '公告日期',
    `f_ann_date` DATE NULL COMMENT '实际公告日期',
    `end_date` DATE NOT NULL COMMENT '报告期',
    `report_type` VARCHAR(64) NOT NULL COMMENT '报表类型',
    `comp_type` VARCHAR(64) NULL COMMENT '公司类型(1一般工商业2银行3保险4证券7多元金融)',
    `end_type` VARCHAR(64) NULL COMMENT '报告期类型',
    `total_share` DECIMAL(38,18) NULL COMMENT '期末总股本',
    `cap_rese` DECIMAL(38,18) NULL COMMENT '资本公积金',
    `undistr_porfit` DECIMAL(38,18) NULL COMMENT '未分配利润',
    `surplus_rese` DECIMAL(38,18) NULL COMMENT '盈余公积金',
    `special_rese` DECIMAL(38,18) NULL COMMENT '专项储备',
    `money_cap` DECIMAL(38,18) NULL COMMENT '货币资金',
    `trad_asset` DECIMAL(38,18) NULL COMMENT '交易性金融资产',
    `notes_receiv` DECIMAL(38,18) NULL COMMENT '应收票据',
    `accounts_receiv` DECIMAL(38,18) NULL COMMENT '应收账款',
    `oth_receiv` DECIMAL(38,18) NULL COMMENT '其他应收款',
    `prepayment` DECIMAL(38,18) NULL COMMENT '预付款项',
    `div_receiv` DECIMAL(38,18) NULL COMMENT '应收股利',
    `int_receiv` DECIMAL(38,18) NULL COMMENT '应收利息',
    `inventories` DECIMAL(38,18) NULL COMMENT '存货',
    `amor_exp` DECIMAL(38,18) NULL COMMENT '待摊费用',
    `nca_within_1y` DECIMAL(38,18) NULL COMMENT '一年内到期的非流动资产',
    `sett_rsrv` DECIMAL(38,18) NULL COMMENT '结算备付金',
    `loanto_oth_bank_fi` DECIMAL(38,18) NULL COMMENT '拆出资金',
    `premium_receiv` DECIMAL(38,18) NULL COMMENT '应收保费',
    `reinsur_receiv` DECIMAL(38,18) NULL COMMENT '应收分保账款',
    `reinsur_res_receiv` DECIMAL(38,18) NULL COMMENT '应收分保合同准备金',
    `pur_resale_fa` DECIMAL(38,18) NULL COMMENT '买入返售金融资产',
    `oth_cur_assets` DECIMAL(38,18) NULL COMMENT '其他流动资产',
    `total_cur_assets` DECIMAL(38,18) NULL COMMENT '流动资产合计',
    `fa_avail_for_sale` DECIMAL(38,18) NULL COMMENT '可供出售金融资产',
    `htm_invest` DECIMAL(38,18) NULL COMMENT '持有至到期投资',
    `lt_eqt_invest` DECIMAL(38,18) NULL COMMENT '长期股权投资',
    `invest_real_estate` DECIMAL(38,18) NULL COMMENT '投资性房地产',
    `time_deposits` DECIMAL(38,18) NULL COMMENT '定期存款',
    `oth_assets` DECIMAL(38,18) NULL COMMENT '其他资产',
    `lt_rec` DECIMAL(38,18) NULL COMMENT '长期应收款',
    `fix_assets` DECIMAL(38,18) NULL COMMENT '固定资产',
    `cip` DECIMAL(38,18) NULL COMMENT '在建工程',
    `const_materials` DECIMAL(38,18) NULL COMMENT '工程物资',
    `fixed_assets_disp` DECIMAL(38,18) NULL COMMENT '固定资产清理',
    `produc_bio_assets` DECIMAL(38,18) NULL COMMENT '生产性生物资产',
    `oil_and_gas_assets` DECIMAL(38,18) NULL COMMENT '油气资产',
    `intan_assets` DECIMAL(38,18) NULL COMMENT '无形资产',
    `r_and_d` DECIMAL(38,18) NULL COMMENT '研发支出',
    `goodwill` DECIMAL(38,18) NULL COMMENT '商誉',
    `lt_amor_exp` DECIMAL(38,18) NULL COMMENT '长期待摊费用',
    `defer_tax_assets` DECIMAL(38,18) NULL COMMENT '递延所得税资产',
    `decr_in_disbur` DECIMAL(38,18) NULL COMMENT '发放贷款及垫款',
    `oth_nca` DECIMAL(38,18) NULL COMMENT '其他非流动资产',
    `total_nca` DECIMAL(38,18) NULL COMMENT '非流动资产合计',
    `cash_reser_cb` DECIMAL(38,18) NULL COMMENT '现金及存放中央银行款项',
    `depos_in_oth_bfi` DECIMAL(38,18) NULL COMMENT '存放同业和其它金融机构款项',
    `prec_metals` DECIMAL(38,18) NULL COMMENT '贵金属',
    `deriv_assets` DECIMAL(38,18) NULL COMMENT '衍生金融资产',
    `rr_reins_une_prem` DECIMAL(38,18) NULL COMMENT '应收分保未到期责任准备金',
    `rr_reins_outstd_cla` DECIMAL(38,18) NULL COMMENT '应收分保未决赔款准备金',
    `rr_reins_lins_liab` DECIMAL(38,18) NULL COMMENT '应收分保寿险责任准备金',
    `rr_reins_lthins_liab` DECIMAL(38,18) NULL COMMENT '应收分保长期健康险责任准备金',
    `refund_depos` DECIMAL(38,18) NULL COMMENT '存出保证金',
    `ph_pledge_loans` DECIMAL(38,18) NULL COMMENT '保户质押贷款',
    `refund_cap_depos` DECIMAL(38,18) NULL COMMENT '存出资本保证金',
    `indep_acct_assets` DECIMAL(38,18) NULL COMMENT '独立账户资产',
    `client_depos` DECIMAL(38,18) NULL COMMENT '其中：客户资金存款',
    `client_prov` DECIMAL(38,18) NULL COMMENT '其中：客户备付金',
    `transac_seat_fee` DECIMAL(38,18) NULL COMMENT '其中:交易席位费',
    `invest_as_receiv` DECIMAL(38,18) NULL COMMENT '应收款项类投资',
    `total_assets` DECIMAL(38,18) NULL COMMENT '资产总计',
    `lt_borr` DECIMAL(38,18) NULL COMMENT '长期借款',
    `st_borr` DECIMAL(38,18) NULL COMMENT '短期借款',
    `cb_borr` DECIMAL(38,18) NULL COMMENT '向中央银行借款',
    `depos_ib_deposits` DECIMAL(38,18) NULL COMMENT '吸收存款及同业存放',
    `loan_oth_bank` DECIMAL(38,18) NULL COMMENT '拆入资金',
    `trading_fl` DECIMAL(38,18) NULL COMMENT '交易性金融负债',
    `notes_payable` DECIMAL(38,18) NULL COMMENT '应付票据',
    `acct_payable` DECIMAL(38,18) NULL COMMENT '应付账款',
    `adv_receipts` DECIMAL(38,18) NULL COMMENT '预收款项',
    `sold_for_repur_fa` DECIMAL(38,18) NULL COMMENT '卖出回购金融资产款',
    `comm_payable` DECIMAL(38,18) NULL COMMENT '应付手续费及佣金',
    `payroll_payable` DECIMAL(38,18) NULL COMMENT '应付职工薪酬',
    `taxes_payable` DECIMAL(38,18) NULL COMMENT '应交税费',
    `int_payable` DECIMAL(38,18) NULL COMMENT '应付利息',
    `div_payable` DECIMAL(38,18) NULL COMMENT '应付股利',
    `oth_payable` DECIMAL(38,18) NULL COMMENT '其他应付款',
    `acc_exp` DECIMAL(38,18) NULL COMMENT '预提费用',
    `deferred_inc` DECIMAL(38,18) NULL COMMENT '递延收益',
    `st_bonds_payable` DECIMAL(38,18) NULL COMMENT '应付短期债券',
    `payable_to_reinsurer` DECIMAL(38,18) NULL COMMENT '应付分保账款',
    `rsrv_insur_cont` DECIMAL(38,18) NULL COMMENT '保险合同准备金',
    `acting_trading_sec` DECIMAL(38,18) NULL COMMENT '代理买卖证券款',
    `acting_uw_sec` DECIMAL(38,18) NULL COMMENT '代理承销证券款',
    `non_cur_liab_due_1y` DECIMAL(38,18) NULL COMMENT '一年内到期的非流动负债',
    `oth_cur_liab` DECIMAL(38,18) NULL COMMENT '其他流动负债',
    `total_cur_liab` DECIMAL(38,18) NULL COMMENT '流动负债合计',
    `bond_payable` DECIMAL(38,18) NULL COMMENT '应付债券',
    `lt_payable` DECIMAL(38,18) NULL COMMENT '长期应付款',
    `specific_payables` DECIMAL(38,18) NULL COMMENT '专项应付款',
    `estimated_liab` DECIMAL(38,18) NULL COMMENT '预计负债',
    `defer_tax_liab` DECIMAL(38,18) NULL COMMENT '递延所得税负债',
    `defer_inc_non_cur_liab` DECIMAL(38,18) NULL COMMENT '递延收益-非流动负债',
    `oth_ncl` DECIMAL(38,18) NULL COMMENT '其他非流动负债',
    `total_ncl` DECIMAL(38,18) NULL COMMENT '非流动负债合计',
    `depos_oth_bfi` DECIMAL(38,18) NULL COMMENT '同业和其它金融机构存放款项',
    `deriv_liab` DECIMAL(38,18) NULL COMMENT '衍生金融负债',
    `depos` DECIMAL(38,18) NULL COMMENT '吸收存款',
    `agency_bus_liab` DECIMAL(38,18) NULL COMMENT '代理业务负债',
    `oth_liab` DECIMAL(38,18) NULL COMMENT '其他负债',
    `prem_receiv_adva` DECIMAL(38,18) NULL COMMENT '预收保费',
    `depos_received` DECIMAL(38,18) NULL COMMENT '存入保证金',
    `ph_invest` DECIMAL(38,18) NULL COMMENT '保户储金及投资款',
    `reser_une_prem` DECIMAL(38,18) NULL COMMENT '未到期责任准备金',
    `reser_outstd_claims` DECIMAL(38,18) NULL COMMENT '未决赔款准备金',
    `reser_lins_liab` DECIMAL(38,18) NULL COMMENT '寿险责任准备金',
    `reser_lthins_liab` DECIMAL(38,18) NULL COMMENT '长期健康险责任准备金',
    `indept_acc_liab` DECIMAL(38,18) NULL COMMENT '独立账户负债',
    `pledge_borr` DECIMAL(38,18) NULL COMMENT '其中:质押借款',
    `indem_payable` DECIMAL(38,18) NULL COMMENT '应付赔付款',
    `policy_div_payable` DECIMAL(38,18) NULL COMMENT '应付保单红利',
    `total_liab` DECIMAL(38,18) NULL COMMENT '负债合计',
    `treasury_share` DECIMAL(38,18) NULL COMMENT '减:库存股',
    `ordin_risk_reser` DECIMAL(38,18) NULL COMMENT '一般风险准备',
    `forex_differ` DECIMAL(38,18) NULL COMMENT '外币报表折算差额',
    `invest_loss_unconf` DECIMAL(38,18) NULL COMMENT '未确认的投资损失',
    `minority_int` DECIMAL(38,18) NULL COMMENT '少数股东权益',
    `total_hldr_eqy_exc_min_int` DECIMAL(38,18) NULL COMMENT '股东权益合计(不含少数股东权益)',
    `total_hldr_eqy_inc_min_int` DECIMAL(38,18) NULL COMMENT '股东权益合计(含少数股东权益)',
    `total_liab_hldr_eqy` DECIMAL(38,18) NULL COMMENT '负债及股东权益总计',
    `lt_payroll_payable` DECIMAL(38,18) NULL COMMENT '长期应付职工薪酬',
    `oth_comp_income` DECIMAL(38,18) NULL COMMENT '其他综合收益',
    `oth_eqt_tools` DECIMAL(38,18) NULL COMMENT '其他权益工具',
    `oth_eqt_tools_p_shr` DECIMAL(38,18) NULL COMMENT '其他权益工具(优先股)',
    `lending_funds` DECIMAL(38,18) NULL COMMENT '融出资金',
    `acc_receivable` DECIMAL(38,18) NULL COMMENT '应收款项',
    `st_fin_payable` DECIMAL(38,18) NULL COMMENT '应付短期融资款',
    `payables` DECIMAL(38,18) NULL COMMENT '应付款项',
    `hfs_assets` DECIMAL(38,18) NULL COMMENT '持有待售的资产',
    `hfs_sales` DECIMAL(38,18) NULL COMMENT '持有待售的负债',
    `cost_fin_assets` DECIMAL(38,18) NULL COMMENT '以摊余成本计量的金融资产',
    `fair_value_fin_assets` DECIMAL(38,18) NULL COMMENT '以公允价值计量且其变动计入其他综合收益的金融资产',
    `contract_assets` DECIMAL(38,18) NULL COMMENT '合同资产',
    `contract_liab` DECIMAL(38,18) NULL COMMENT '合同负债',
    `accounts_receiv_bill` DECIMAL(38,18) NULL COMMENT '应收票据及应收账款',
    `accounts_pay` DECIMAL(38,18) NULL COMMENT '应付票据及应付账款',
    `oth_rcv_total` DECIMAL(38,18) NULL COMMENT '其他应收款(合计)（元）',
    `fix_assets_total` DECIMAL(38,18) NULL COMMENT '固定资产(合计)(元)',
    `cip_total` DECIMAL(38,18) NULL COMMENT '在建工程(合计)(元)',
    `oth_pay_total` DECIMAL(38,18) NULL COMMENT '其他应付款(合计)(元)',
    `long_pay_total` DECIMAL(38,18) NULL COMMENT '长期应付款(合计)(元)',
    `debt_invest` DECIMAL(38,18) NULL COMMENT '债权投资(元)',
    `oth_debt_invest` DECIMAL(38,18) NULL COMMENT '其他债权投资(元)',
    `update_flag` VARCHAR(64) NULL COMMENT '来源数据更新标识',
    `source_plugin` VARCHAR(64) NOT NULL COMMENT '来源插件标识',
    `source_api` VARCHAR(64) NOT NULL COMMENT '来源接口名称',
    `ingested_at` DATETIME(3) NOT NULL COMMENT '数据入库时间（UTC，毫秒精度）',
    -- 以来源业务键唯一标识记录，支持重复下载时更新同一条数据。
    PRIMARY KEY (`ts_code`, `end_date`, `report_type`, `ann_date`),
    -- 支持按公告日期查询。
    KEY `idx_balancesheet_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='资产负债表';

CREATE TABLE `tushare_pro__cashflow` (
    `ts_code` VARCHAR(64) NOT NULL COMMENT 'TS股票代码',
    `ann_date` DATE NOT NULL COMMENT '公告日期',
    `f_ann_date` DATE NULL COMMENT '实际公告日期',
    `end_date` DATE NOT NULL COMMENT '报告期',
    `comp_type` VARCHAR(64) NULL COMMENT '公司类型(1一般工商业2银行3保险4证券7多元金融)',
    `report_type` VARCHAR(64) NOT NULL COMMENT '报表类型',
    `end_type` VARCHAR(64) NULL COMMENT '报告期类型',
    `net_profit` DECIMAL(38,18) NULL COMMENT '净利润',
    `finan_exp` DECIMAL(38,18) NULL COMMENT '财务费用',
    `c_fr_sale_sg` DECIMAL(38,18) NULL COMMENT '销售商品、提供劳务收到的现金',
    `recp_tax_rends` DECIMAL(38,18) NULL COMMENT '收到的税费返还',
    `n_depos_incr_fi` DECIMAL(38,18) NULL COMMENT '客户存款和同业存放款项净增加额',
    `n_incr_loans_cb` DECIMAL(38,18) NULL COMMENT '向中央银行借款净增加额',
    `n_inc_borr_oth_fi` DECIMAL(38,18) NULL COMMENT '向其他金融机构拆入资金净增加额',
    `prem_fr_orig_contr` DECIMAL(38,18) NULL COMMENT '收到原保险合同保费取得的现金',
    `n_incr_insured_dep` DECIMAL(38,18) NULL COMMENT '保户储金净增加额',
    `n_reinsur_prem` DECIMAL(38,18) NULL COMMENT '收到再保业务现金净额',
    `n_incr_disp_tfa` DECIMAL(38,18) NULL COMMENT '处置交易性金融资产净增加额',
    `ifc_cash_incr` DECIMAL(38,18) NULL COMMENT '收取利息和手续费净增加额',
    `n_incr_disp_faas` DECIMAL(38,18) NULL COMMENT '处置可供出售金融资产净增加额',
    `n_incr_loans_oth_bank` DECIMAL(38,18) NULL COMMENT '拆入资金净增加额',
    `n_cap_incr_repur` DECIMAL(38,18) NULL COMMENT '回购业务资金净增加额',
    `c_fr_oth_operate_a` DECIMAL(38,18) NULL COMMENT '收到其他与经营活动有关的现金',
    `c_inf_fr_operate_a` DECIMAL(38,18) NULL COMMENT '经营活动现金流入小计',
    `c_paid_goods_s` DECIMAL(38,18) NULL COMMENT '购买商品、接受劳务支付的现金',
    `c_paid_to_for_empl` DECIMAL(38,18) NULL COMMENT '支付给职工以及为职工支付的现金',
    `c_paid_for_taxes` DECIMAL(38,18) NULL COMMENT '支付的各项税费',
    `n_incr_clt_loan_adv` DECIMAL(38,18) NULL COMMENT '客户贷款及垫款净增加额',
    `n_incr_dep_cbob` DECIMAL(38,18) NULL COMMENT '存放央行和同业款项净增加额',
    `c_pay_claims_orig_inco` DECIMAL(38,18) NULL COMMENT '支付原保险合同赔付款项的现金',
    `pay_handling_chrg` DECIMAL(38,18) NULL COMMENT '支付手续费的现金',
    `pay_comm_insur_plcy` DECIMAL(38,18) NULL COMMENT '支付保单红利的现金',
    `oth_cash_pay_oper_act` DECIMAL(38,18) NULL COMMENT '支付其他与经营活动有关的现金',
    `st_cash_out_act` DECIMAL(38,18) NULL COMMENT '经营活动现金流出小计',
    `n_cashflow_act` DECIMAL(38,18) NULL COMMENT '经营活动产生的现金流量净额',
    `oth_recp_ral_inv_act` DECIMAL(38,18) NULL COMMENT '收到其他与投资活动有关的现金',
    `c_disp_withdrwl_invest` DECIMAL(38,18) NULL COMMENT '收回投资收到的现金',
    `c_recp_return_invest` DECIMAL(38,18) NULL COMMENT '取得投资收益收到的现金',
    `n_recp_disp_fiolta` DECIMAL(38,18) NULL COMMENT '处置固定资产、无形资产和其他长期资产收回的现金净额',
    `n_recp_disp_sobu` DECIMAL(38,18) NULL COMMENT '处置子公司及其他营业单位收到的现金净额',
    `stot_inflows_inv_act` DECIMAL(38,18) NULL COMMENT '投资活动现金流入小计',
    `c_pay_acq_const_fiolta` DECIMAL(38,18) NULL COMMENT '购建固定资产、无形资产和其他长期资产支付的现金',
    `c_paid_invest` DECIMAL(38,18) NULL COMMENT '投资支付的现金',
    `n_disp_subs_oth_biz` DECIMAL(38,18) NULL COMMENT '取得子公司及其他营业单位支付的现金净额',
    `oth_pay_ral_inv_act` DECIMAL(38,18) NULL COMMENT '支付其他与投资活动有关的现金',
    `n_incr_pledge_loan` DECIMAL(38,18) NULL COMMENT '质押贷款净增加额',
    `stot_out_inv_act` DECIMAL(38,18) NULL COMMENT '投资活动现金流出小计',
    `n_cashflow_inv_act` DECIMAL(38,18) NULL COMMENT '投资活动产生的现金流量净额',
    `c_recp_borrow` DECIMAL(38,18) NULL COMMENT '取得借款收到的现金',
    `proc_issue_bonds` DECIMAL(38,18) NULL COMMENT '发行债券收到的现金',
    `oth_cash_recp_ral_fnc_act` DECIMAL(38,18) NULL COMMENT '收到其他与筹资活动有关的现金',
    `stot_cash_in_fnc_act` DECIMAL(38,18) NULL COMMENT '筹资活动现金流入小计',
    `free_cashflow` DECIMAL(38,18) NULL COMMENT '企业自由现金流量',
    `c_prepay_amt_borr` DECIMAL(38,18) NULL COMMENT '偿还债务支付的现金',
    `c_pay_dist_dpcp_int_exp` DECIMAL(38,18) NULL COMMENT '分配股利、利润或偿付利息支付的现金',
    `incl_dvd_profit_paid_sc_ms` DECIMAL(38,18) NULL COMMENT '其中:子公司支付给少数股东的股利、利润',
    `oth_cashpay_ral_fnc_act` DECIMAL(38,18) NULL COMMENT '支付其他与筹资活动有关的现金',
    `stot_cashout_fnc_act` DECIMAL(38,18) NULL COMMENT '筹资活动现金流出小计',
    `n_cash_flows_fnc_act` DECIMAL(38,18) NULL COMMENT '筹资活动产生的现金流量净额',
    `eff_fx_flu_cash` DECIMAL(38,18) NULL COMMENT '汇率变动对现金的影响',
    `n_incr_cash_cash_equ` DECIMAL(38,18) NULL COMMENT '现金及现金等价物净增加额',
    `c_cash_equ_beg_period` DECIMAL(38,18) NULL COMMENT '期初现金及现金等价物余额',
    `c_cash_equ_end_period` DECIMAL(38,18) NULL COMMENT '期末现金及现金等价物余额',
    `c_recp_cap_contrib` DECIMAL(38,18) NULL COMMENT '吸收投资收到的现金',
    `incl_cash_rec_saims` DECIMAL(38,18) NULL COMMENT '其中:子公司吸收少数股东投资收到的现金',
    `uncon_invest_loss` DECIMAL(38,18) NULL COMMENT '未确认投资损失',
    `prov_depr_assets` DECIMAL(38,18) NULL COMMENT '加:资产减值准备',
    `depr_fa_coga_dpba` DECIMAL(38,18) NULL COMMENT '固定资产折旧、油气资产折耗、生产性生物资产折旧',
    `amort_intang_assets` DECIMAL(38,18) NULL COMMENT '无形资产摊销',
    `lt_amort_deferred_exp` DECIMAL(38,18) NULL COMMENT '长期待摊费用摊销',
    `decr_deferred_exp` DECIMAL(38,18) NULL COMMENT '待摊费用减少',
    `incr_acc_exp` DECIMAL(38,18) NULL COMMENT '预提费用增加',
    `loss_disp_fiolta` DECIMAL(38,18) NULL COMMENT '处置固定、无形资产和其他长期资产的损失',
    `loss_scr_fa` DECIMAL(38,18) NULL COMMENT '固定资产报废损失',
    `loss_fv_chg` DECIMAL(38,18) NULL COMMENT '公允价值变动损失',
    `invest_loss` DECIMAL(38,18) NULL COMMENT '投资损失',
    `decr_def_inc_tax_assets` DECIMAL(38,18) NULL COMMENT '递延所得税资产减少',
    `incr_def_inc_tax_liab` DECIMAL(38,18) NULL COMMENT '递延所得税负债增加',
    `decr_inventories` DECIMAL(38,18) NULL COMMENT '存货的减少',
    `decr_oper_payable` DECIMAL(38,18) NULL COMMENT '经营性应收项目的减少',
    `incr_oper_payable` DECIMAL(38,18) NULL COMMENT '经营性应付项目的增加',
    `others` DECIMAL(38,18) NULL COMMENT '其他',
    `im_net_cashflow_oper_act` DECIMAL(38,18) NULL COMMENT '经营活动产生的现金流量净额(间接法)',
    `conv_debt_into_cap` DECIMAL(38,18) NULL COMMENT '债务转为资本',
    `conv_copbonds_due_within_1y` DECIMAL(38,18) NULL COMMENT '一年内到期的可转换公司债券',
    `fa_fnc_leases` DECIMAL(38,18) NULL COMMENT '融资租入固定资产',
    `im_n_incr_cash_equ` DECIMAL(38,18) NULL COMMENT '现金及现金等价物净增加额(间接法)',
    `net_dism_capital_add` DECIMAL(38,18) NULL COMMENT '拆出资金净增加额',
    `net_cash_rece_sec` DECIMAL(38,18) NULL COMMENT '代理买卖证券收到的现金净额(元)',
    `credit_impa_loss` DECIMAL(38,18) NULL COMMENT '信用减值损失',
    `use_right_asset_dep` DECIMAL(38,18) NULL COMMENT '使用权资产折旧',
    `oth_loss_asset` DECIMAL(38,18) NULL COMMENT '其他资产减值损失',
    `end_bal_cash` DECIMAL(38,18) NULL COMMENT '现金的期末余额',
    `beg_bal_cash` DECIMAL(38,18) NULL COMMENT '减:现金的期初余额',
    `end_bal_cash_equ` DECIMAL(38,18) NULL COMMENT '加:现金等价物的期末余额',
    `beg_bal_cash_equ` DECIMAL(38,18) NULL COMMENT '减:现金等价物的期初余额',
    `update_flag` VARCHAR(64) NULL COMMENT '来源数据更新标识',
    `source_plugin` VARCHAR(64) NOT NULL COMMENT '来源插件标识',
    `source_api` VARCHAR(64) NOT NULL COMMENT '来源接口名称',
    `ingested_at` DATETIME(3) NOT NULL COMMENT '数据入库时间（UTC，毫秒精度）',
    -- 以来源业务键唯一标识记录，支持重复下载时更新同一条数据。
    PRIMARY KEY (`ts_code`, `end_date`, `report_type`, `ann_date`),
    -- 支持按公告日期查询。
    KEY `idx_cashflow_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='现金流量表';

CREATE TABLE `tushare_pro__fina_indicator` (
    `ts_code` VARCHAR(64) NOT NULL COMMENT 'TS代码',
    `ann_date` DATE NOT NULL COMMENT '公告日期',
    `end_date` DATE NOT NULL COMMENT '报告期',
    `eps` DECIMAL(38,18) NULL COMMENT '基本每股收益',
    `dt_eps` DECIMAL(38,18) NULL COMMENT '稀释每股收益',
    `total_revenue_ps` DECIMAL(38,18) NULL COMMENT '每股营业总收入',
    `revenue_ps` DECIMAL(38,18) NULL COMMENT '每股营业收入',
    `capital_rese_ps` DECIMAL(38,18) NULL COMMENT '每股资本公积',
    `surplus_rese_ps` DECIMAL(38,18) NULL COMMENT '每股盈余公积',
    `undist_profit_ps` DECIMAL(38,18) NULL COMMENT '每股未分配利润',
    `extra_item` DECIMAL(38,18) NULL COMMENT '非经常性损益',
    `profit_dedt` DECIMAL(38,18) NULL COMMENT '扣除非经常性损益后的净利润（扣非净利润）',
    `gross_margin` DECIMAL(38,18) NULL COMMENT '毛利',
    `current_ratio` DECIMAL(38,18) NULL COMMENT '流动比率',
    `quick_ratio` DECIMAL(38,18) NULL COMMENT '速动比率',
    `cash_ratio` DECIMAL(38,18) NULL COMMENT '保守速动比率',
    `ar_turn` DECIMAL(38,18) NULL COMMENT '应收账款周转率',
    `ca_turn` DECIMAL(38,18) NULL COMMENT '流动资产周转率',
    `fa_turn` DECIMAL(38,18) NULL COMMENT '固定资产周转率',
    `assets_turn` DECIMAL(38,18) NULL COMMENT '总资产周转率',
    `op_income` DECIMAL(38,18) NULL COMMENT '经营活动净收益',
    `ebit` DECIMAL(38,18) NULL COMMENT '息税前利润',
    `ebitda` DECIMAL(38,18) NULL COMMENT '息税折旧摊销前利润',
    `fcff` DECIMAL(38,18) NULL COMMENT '企业自由现金流量',
    `fcfe` DECIMAL(38,18) NULL COMMENT '股权自由现金流量',
    `current_exint` DECIMAL(38,18) NULL COMMENT '无息流动负债',
    `noncurrent_exint` DECIMAL(38,18) NULL COMMENT '无息非流动负债',
    `interestdebt` DECIMAL(38,18) NULL COMMENT '带息债务',
    `netdebt` DECIMAL(38,18) NULL COMMENT '净债务',
    `tangible_asset` DECIMAL(38,18) NULL COMMENT '有形资产',
    `working_capital` DECIMAL(38,18) NULL COMMENT '营运资金',
    `networking_capital` DECIMAL(38,18) NULL COMMENT '营运流动资本',
    `invest_capital` DECIMAL(38,18) NULL COMMENT '全部投入资本',
    `retained_earnings` DECIMAL(38,18) NULL COMMENT '留存收益',
    `diluted2_eps` DECIMAL(38,18) NULL COMMENT '期末摊薄每股收益',
    `bps` DECIMAL(38,18) NULL COMMENT '每股净资产',
    `ocfps` DECIMAL(38,18) NULL COMMENT '每股经营活动产生的现金流量净额',
    `retainedps` DECIMAL(38,18) NULL COMMENT '每股留存收益',
    `cfps` DECIMAL(38,18) NULL COMMENT '每股现金流量净额',
    `ebit_ps` DECIMAL(38,18) NULL COMMENT '每股息税前利润',
    `fcff_ps` DECIMAL(38,18) NULL COMMENT '每股企业自由现金流量',
    `fcfe_ps` DECIMAL(38,18) NULL COMMENT '每股股东自由现金流量',
    `netprofit_margin` DECIMAL(38,18) NULL COMMENT '销售净利率',
    `grossprofit_margin` DECIMAL(38,18) NULL COMMENT '销售毛利率',
    `cogs_of_sales` DECIMAL(38,18) NULL COMMENT '销售成本率',
    `expense_of_sales` DECIMAL(38,18) NULL COMMENT '销售期间费用率',
    `profit_to_gr` DECIMAL(38,18) NULL COMMENT '净利润/营业总收入',
    `saleexp_to_gr` DECIMAL(38,18) NULL COMMENT '销售费用/营业总收入',
    `adminexp_of_gr` DECIMAL(38,18) NULL COMMENT '管理费用/营业总收入',
    `finaexp_of_gr` DECIMAL(38,18) NULL COMMENT '财务费用/营业总收入',
    `impai_ttm` DECIMAL(38,18) NULL COMMENT '资产减值损失/营业总收入',
    `gc_of_gr` DECIMAL(38,18) NULL COMMENT '营业总成本/营业总收入',
    `op_of_gr` DECIMAL(38,18) NULL COMMENT '营业利润/营业总收入',
    `ebit_of_gr` DECIMAL(38,18) NULL COMMENT '息税前利润/营业总收入',
    `roe` DECIMAL(38,18) NULL COMMENT '净资产收益率',
    `roe_waa` DECIMAL(38,18) NULL COMMENT '加权平均净资产收益率',
    `roe_dt` DECIMAL(38,18) NULL COMMENT '净资产收益率(扣除非经常损益)',
    `roa` DECIMAL(38,18) NULL COMMENT '总资产报酬率',
    `npta` DECIMAL(38,18) NULL COMMENT '总资产净利润',
    `roic` DECIMAL(38,18) NULL COMMENT '投入资本回报率',
    `roe_yearly` DECIMAL(38,18) NULL COMMENT '年化净资产收益率',
    `roa2_yearly` DECIMAL(38,18) NULL COMMENT '年化总资产报酬率',
    `debt_to_assets` DECIMAL(38,18) NULL COMMENT '资产负债率',
    `assets_to_eqt` DECIMAL(38,18) NULL COMMENT '权益乘数',
    `dp_assets_to_eqt` DECIMAL(38,18) NULL COMMENT '权益乘数(杜邦分析)',
    `ca_to_assets` DECIMAL(38,18) NULL COMMENT '流动资产/总资产',
    `nca_to_assets` DECIMAL(38,18) NULL COMMENT '非流动资产/总资产',
    `tbassets_to_totalassets` DECIMAL(38,18) NULL COMMENT '有形资产/总资产',
    `int_to_talcap` DECIMAL(38,18) NULL COMMENT '带息债务/全部投入资本',
    `eqt_to_talcapital` DECIMAL(38,18) NULL COMMENT '归属于母公司的股东权益/全部投入资本',
    `currentdebt_to_debt` DECIMAL(38,18) NULL COMMENT '流动负债/负债合计',
    `longdeb_to_debt` DECIMAL(38,18) NULL COMMENT '非流动负债/负债合计',
    `ocf_to_shortdebt` DECIMAL(38,18) NULL COMMENT '经营活动产生的现金流量净额/流动负债',
    `debt_to_eqt` DECIMAL(38,18) NULL COMMENT '产权比率',
    `eqt_to_debt` DECIMAL(38,18) NULL COMMENT '归属于母公司的股东权益/负债合计',
    `eqt_to_interestdebt` DECIMAL(38,18) NULL COMMENT '归属于母公司的股东权益/带息债务',
    `tangibleasset_to_debt` DECIMAL(38,18) NULL COMMENT '有形资产/负债合计',
    `tangasset_to_intdebt` DECIMAL(38,18) NULL COMMENT '有形资产/带息债务',
    `tangibleasset_to_netdebt` DECIMAL(38,18) NULL COMMENT '有形资产/净债务',
    `ocf_to_debt` DECIMAL(38,18) NULL COMMENT '经营活动产生的现金流量净额/负债合计',
    `turn_days` DECIMAL(38,18) NULL COMMENT '营业周期',
    `roa_yearly` DECIMAL(38,18) NULL COMMENT '年化总资产净利率',
    `roa_dp` DECIMAL(38,18) NULL COMMENT '总资产净利率(杜邦分析)',
    `fixed_assets` DECIMAL(38,18) NULL COMMENT '固定资产合计',
    `profit_to_op` DECIMAL(38,18) NULL COMMENT '利润总额／营业收入',
    `q_saleexp_to_gr` DECIMAL(38,18) NULL COMMENT '销售费用／营业总收入 (单季度)',
    `q_gc_to_gr` DECIMAL(38,18) NULL COMMENT '营业总成本／营业总收入 (单季度)',
    `q_roe` DECIMAL(38,18) NULL COMMENT '净资产收益率(单季度)',
    `q_dt_roe` DECIMAL(38,18) NULL COMMENT '净资产单季度收益率(扣除非经常损益)',
    `q_npta` DECIMAL(38,18) NULL COMMENT '总资产净利润(单季度)',
    `q_ocf_to_sales` DECIMAL(38,18) NULL COMMENT '经营活动产生的现金流量净额／营业收入(单季度)',
    `basic_eps_yoy` DECIMAL(38,18) NULL COMMENT '基本每股收益同比增长率(%)',
    `dt_eps_yoy` DECIMAL(38,18) NULL COMMENT '稀释每股收益同比增长率(%)',
    `cfps_yoy` DECIMAL(38,18) NULL COMMENT '每股经营活动产生的现金流量净额同比增长率(%)',
    `op_yoy` DECIMAL(38,18) NULL COMMENT '营业利润同比增长率(%)',
    `ebt_yoy` DECIMAL(38,18) NULL COMMENT '利润总额同比增长率(%)',
    `netprofit_yoy` DECIMAL(38,18) NULL COMMENT '归属母公司股东的净利润同比增长率(%)',
    `dt_netprofit_yoy` DECIMAL(38,18) NULL COMMENT '归属母公司股东的净利润-扣除非经常损益同比增长率(%)',
    `ocf_yoy` DECIMAL(38,18) NULL COMMENT '经营活动产生的现金流量净额同比增长率(%)',
    `roe_yoy` DECIMAL(38,18) NULL COMMENT '净资产收益率(摊薄)同比增长率(%)',
    `bps_yoy` DECIMAL(38,18) NULL COMMENT '每股净资产相对年初增长率(%)',
    `assets_yoy` DECIMAL(38,18) NULL COMMENT '资产总计相对年初增长率(%)',
    `eqt_yoy` DECIMAL(38,18) NULL COMMENT '归属母公司的股东权益相对年初增长率(%)',
    `tr_yoy` DECIMAL(38,18) NULL COMMENT '营业总收入同比增长率(%)',
    `or_yoy` DECIMAL(38,18) NULL COMMENT '营业收入同比增长率(%)',
    `q_sales_yoy` DECIMAL(38,18) NULL COMMENT '营业收入同比增长率(%)(单季度)',
    `q_op_qoq` DECIMAL(38,18) NULL COMMENT '营业利润环比增长率(%)(单季度)',
    `equity_yoy` DECIMAL(38,18) NULL COMMENT '净资产同比增长率',
    `source_plugin` VARCHAR(64) NOT NULL COMMENT '来源插件标识',
    `source_api` VARCHAR(64) NOT NULL COMMENT '来源接口名称',
    `ingested_at` DATETIME(3) NOT NULL COMMENT '数据入库时间（UTC，毫秒精度）',
    -- 以来源业务键唯一标识记录，支持重复下载时更新同一条数据。
    PRIMARY KEY (`ts_code`, `end_date`, `ann_date`),
    -- 支持按公告日期查询。
    KEY `idx_fina_indicator_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='财务指标';

CREATE TABLE `tushare_pro__fina_audit` (
    `ts_code` VARCHAR(64) NOT NULL COMMENT 'TS股票代码',
    `ann_date` DATE NOT NULL COMMENT '公告日期',
    `end_date` DATE NOT NULL COMMENT '报告期',
    `audit_result` VARCHAR(255) NULL COMMENT '审计结果',
    `audit_fees` DECIMAL(38,18) NULL COMMENT '审计总费用（元）',
    `audit_agency` VARCHAR(255) NULL COMMENT '会计事务所',
    `audit_sign` VARCHAR(255) NULL COMMENT '签字会计师',
    `source_plugin` VARCHAR(64) NOT NULL COMMENT '来源插件标识',
    `source_api` VARCHAR(64) NOT NULL COMMENT '来源接口名称',
    `ingested_at` DATETIME(3) NOT NULL COMMENT '数据入库时间（UTC，毫秒精度）',
    -- 以来源业务键唯一标识记录，支持重复下载时更新同一条数据。
    PRIMARY KEY (`ts_code`, `end_date`, `ann_date`),
    -- 支持按公告日期查询。
    KEY `idx_fina_audit_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='财务审计意见';

CREATE TABLE `tushare_pro__fina_mainbz` (
    `ts_code` VARCHAR(64) NOT NULL COMMENT 'TS代码',
    `end_date` DATE NOT NULL COMMENT '报告期',
    `bz_item` VARCHAR(255) NOT NULL COMMENT '主营业务来源',
    `bz_code` VARCHAR(64) NULL COMMENT '主营业务来源类型（P-按产品 D-按地区 I-按行业）',
    `bz_sales` DECIMAL(38,18) NULL COMMENT '主营业务收入(元)',
    `bz_profit` DECIMAL(38,18) NULL COMMENT '主营业务利润(元)',
    `bz_cost` DECIMAL(38,18) NULL COMMENT '主营业务成本(元)',
    `curr_type` VARCHAR(64) NOT NULL COMMENT '货币代码（CNY）',
    `source_plugin` VARCHAR(64) NOT NULL COMMENT '来源插件标识',
    `source_api` VARCHAR(64) NOT NULL COMMENT '来源接口名称',
    `ingested_at` DATETIME(3) NOT NULL COMMENT '数据入库时间（UTC，毫秒精度）',
    -- 以来源业务键唯一标识记录，支持重复下载时更新同一条数据。
    PRIMARY KEY (`ts_code`, `end_date`, `bz_item`, `curr_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='主营业务构成';

CREATE TABLE `tushare_pro__express` (
    `ts_code` VARCHAR(64) NOT NULL COMMENT 'TS股票代码',
    `ann_date` DATE NOT NULL COMMENT '公告日期',
    `end_date` DATE NOT NULL COMMENT '报告期',
    `revenue` DECIMAL(38,18) NULL COMMENT '营业收入(元)',
    `operate_profit` DECIMAL(38,18) NULL COMMENT '营业利润(元)',
    `total_profit` DECIMAL(38,18) NULL COMMENT '利润总额(元)',
    `n_income` DECIMAL(38,18) NULL COMMENT '净利润(元)',
    `total_assets` DECIMAL(38,18) NULL COMMENT '总资产(元)',
    `total_hldr_eqy_exc_min_int` DECIMAL(38,18) NULL COMMENT '股东权益合计(不含少数股东权益)(元)',
    `diluted_eps` DECIMAL(38,18) NULL COMMENT '每股收益(摊薄)(元)',
    `diluted_roe` DECIMAL(38,18) NULL COMMENT '净资产收益率(摊薄)(%)',
    `yoy_net_profit` DECIMAL(38,18) NULL COMMENT '去年同期修正后净利润',
    `bps` DECIMAL(38,18) NULL COMMENT '每股净资产',
    `perf_summary` TEXT NULL COMMENT '业绩简要说明',
    `update_flag` VARCHAR(64) NULL COMMENT '来源数据更新标识',
    `source_plugin` VARCHAR(64) NOT NULL COMMENT '来源插件标识',
    `source_api` VARCHAR(64) NOT NULL COMMENT '来源接口名称',
    `ingested_at` DATETIME(3) NOT NULL COMMENT '数据入库时间（UTC，毫秒精度）',
    -- 以来源业务键唯一标识记录，支持重复下载时更新同一条数据。
    PRIMARY KEY (`ts_code`, `end_date`, `ann_date`),
    -- 支持按公告日期查询。
    KEY `idx_express_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='业绩快报';

CREATE TABLE `tushare_pro__forecast` (
    `ts_code` VARCHAR(64) NOT NULL COMMENT 'TS股票代码',
    `ann_date` DATE NOT NULL COMMENT '公告日期',
    `end_date` DATE NOT NULL COMMENT '报告期',
    `type` VARCHAR(64) NOT NULL COMMENT '业绩预告类型(预增/预减/扭亏/首亏/续亏/续盈/略增/略减)',
    `p_change_min` DECIMAL(38,18) NULL COMMENT '预告净利润变动幅度下限（%）',
    `p_change_max` DECIMAL(38,18) NULL COMMENT '预告净利润变动幅度上限（%）',
    `net_profit_min` DECIMAL(38,18) NULL COMMENT '预告净利润下限（万元）',
    `net_profit_max` DECIMAL(38,18) NULL COMMENT '预告净利润上限（万元）',
    `last_parent_net` DECIMAL(38,18) NULL COMMENT '上年同期归属母公司净利润',
    `first_ann_date` DATE NULL COMMENT '首次公告日',
    `summary` TEXT NULL COMMENT '业绩预告摘要',
    `change_reason` TEXT NULL COMMENT '业绩变动原因',
    `update_flag` VARCHAR(64) NULL COMMENT '来源数据更新标识',
    `source_plugin` VARCHAR(64) NOT NULL COMMENT '来源插件标识',
    `source_api` VARCHAR(64) NOT NULL COMMENT '来源接口名称',
    `ingested_at` DATETIME(3) NOT NULL COMMENT '数据入库时间（UTC，毫秒精度）',
    -- 以来源业务键唯一标识记录，支持重复下载时更新同一条数据。
    PRIMARY KEY (`ts_code`, `end_date`, `ann_date`, `type`),
    -- 支持按公告日期查询。
    KEY `idx_forecast_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='业绩预告';

CREATE TABLE `tushare_pro__disclosure_date` (
    `ts_code` VARCHAR(64) NOT NULL COMMENT 'TS代码',
    `ann_date` DATE NULL COMMENT '最新披露公告日',
    `end_date` DATE NOT NULL COMMENT '报告期',
    `pre_date` DATE NULL COMMENT '预计披露日期',
    `actual_date` DATE NULL COMMENT '实际披露日期',
    `source_plugin` VARCHAR(64) NOT NULL COMMENT '来源插件标识',
    `source_api` VARCHAR(64) NOT NULL COMMENT '来源接口名称',
    `ingested_at` DATETIME(3) NOT NULL COMMENT '数据入库时间（UTC，毫秒精度）',
    -- 以来源业务键唯一标识记录，支持重复下载时更新同一条数据。
    PRIMARY KEY (`ts_code`, `end_date`),
    -- 支持按公告日期查询。
    KEY `idx_disclosure_date_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='财报披露计划';
