SET time_zone = '+00:00';

CREATE TABLE `tushare_pro__income` (
    `ts_code` VARCHAR(64) NOT NULL,
    `ann_date` DATE NOT NULL,
    `f_ann_date` DATE NULL,
    `end_date` DATE NOT NULL,
    `report_type` VARCHAR(64) NOT NULL,
    `comp_type` VARCHAR(64) NULL,
    `end_type` VARCHAR(64) NULL,
    `basic_eps` DECIMAL(38,18) NULL,
    `diluted_eps` DECIMAL(38,18) NULL,
    `total_revenue` DECIMAL(38,18) NULL,
    `revenue` DECIMAL(38,18) NULL,
    `int_income` DECIMAL(38,18) NULL,
    `prem_earned` DECIMAL(38,18) NULL,
    `comm_income` DECIMAL(38,18) NULL,
    `n_commis_income` DECIMAL(38,18) NULL,
    `n_oth_income` DECIMAL(38,18) NULL,
    `n_oth_b_income` DECIMAL(38,18) NULL,
    `prem_income` DECIMAL(38,18) NULL,
    `out_prem` DECIMAL(38,18) NULL,
    `une_prem_reser` DECIMAL(38,18) NULL,
    `reins_income` DECIMAL(38,18) NULL,
    `n_sec_tb_income` DECIMAL(38,18) NULL,
    `n_sec_uw_income` DECIMAL(38,18) NULL,
    `n_asset_mg_income` DECIMAL(38,18) NULL,
    `oth_b_income` DECIMAL(38,18) NULL,
    `fv_value_chg_gain` DECIMAL(38,18) NULL,
    `invest_income` DECIMAL(38,18) NULL,
    `ass_invest_income` DECIMAL(38,18) NULL,
    `forex_gain` DECIMAL(38,18) NULL,
    `total_cogs` DECIMAL(38,18) NULL,
    `oper_cost` DECIMAL(38,18) NULL,
    `int_exp` DECIMAL(38,18) NULL,
    `comm_exp` DECIMAL(38,18) NULL,
    `biz_tax_surchg` DECIMAL(38,18) NULL,
    `sell_exp` DECIMAL(38,18) NULL,
    `admin_exp` DECIMAL(38,18) NULL,
    `fin_exp` DECIMAL(38,18) NULL,
    `assets_impair_loss` DECIMAL(38,18) NULL,
    `prem_refund` DECIMAL(38,18) NULL,
    `compens_payout` DECIMAL(38,18) NULL,
    `reser_insur_liab` DECIMAL(38,18) NULL,
    `div_payt` DECIMAL(38,18) NULL,
    `reins_exp` DECIMAL(38,18) NULL,
    `oper_exp` DECIMAL(38,18) NULL,
    `compens_payout_refu` DECIMAL(38,18) NULL,
    `insur_reser_refu` DECIMAL(38,18) NULL,
    `reins_cost_refund` DECIMAL(38,18) NULL,
    `other_bus_cost` DECIMAL(38,18) NULL,
    `operate_profit` DECIMAL(38,18) NULL,
    `non_oper_income` DECIMAL(38,18) NULL,
    `non_oper_exp` DECIMAL(38,18) NULL,
    `nca_disploss` DECIMAL(38,18) NULL,
    `total_profit` DECIMAL(38,18) NULL,
    `income_tax` DECIMAL(38,18) NULL,
    `n_income` DECIMAL(38,18) NULL,
    `n_income_attr_p` DECIMAL(38,18) NULL,
    `minority_gain` DECIMAL(38,18) NULL,
    `oth_compr_income` DECIMAL(38,18) NULL,
    `t_compr_income` DECIMAL(38,18) NULL,
    `compr_inc_attr_p` DECIMAL(38,18) NULL,
    `compr_inc_attr_m_s` DECIMAL(38,18) NULL,
    `ebit` DECIMAL(38,18) NULL,
    `ebitda` DECIMAL(38,18) NULL,
    `insurance_exp` DECIMAL(38,18) NULL,
    `undist_profit` DECIMAL(38,18) NULL,
    `distable_profit` DECIMAL(38,18) NULL,
    `rd_exp` DECIMAL(38,18) NULL,
    `fin_exp_int_exp` DECIMAL(38,18) NULL,
    `fin_exp_int_inc` DECIMAL(38,18) NULL,
    `transfer_surplus_rese` DECIMAL(38,18) NULL,
    `transfer_housing_imprest` DECIMAL(38,18) NULL,
    `transfer_oth` DECIMAL(38,18) NULL,
    `adj_lossgain` DECIMAL(38,18) NULL,
    `withdra_legal_surplus` DECIMAL(38,18) NULL,
    `withdra_legal_pubfund` DECIMAL(38,18) NULL,
    `withdra_biz_devfund` DECIMAL(38,18) NULL,
    `withdra_rese_fund` DECIMAL(38,18) NULL,
    `withdra_oth_ersu` DECIMAL(38,18) NULL,
    `workers_welfare` DECIMAL(38,18) NULL,
    `distr_profit_shrhder` DECIMAL(38,18) NULL,
    `prfshare_payable_dvd` DECIMAL(38,18) NULL,
    `comshare_payable_dvd` DECIMAL(38,18) NULL,
    `capit_comstock_div` DECIMAL(38,18) NULL,
    `continued_net_profit` DECIMAL(38,18) NULL,
    `update_flag` VARCHAR(64) NULL,
    `source_plugin` VARCHAR(64) NOT NULL,
    `source_api` VARCHAR(64) NOT NULL,
    `ingested_at` DATETIME(3) NOT NULL,
    PRIMARY KEY (`ts_code`, `end_date`, `report_type`, `ann_date`),
    KEY `idx_income_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;

CREATE TABLE `tushare_pro__balancesheet` (
    `ts_code` VARCHAR(64) NOT NULL,
    `ann_date` DATE NOT NULL,
    `f_ann_date` DATE NULL,
    `end_date` DATE NOT NULL,
    `report_type` VARCHAR(64) NOT NULL,
    `comp_type` VARCHAR(64) NULL,
    `end_type` VARCHAR(64) NULL,
    `total_share` DECIMAL(38,18) NULL,
    `cap_rese` DECIMAL(38,18) NULL,
    `undistr_porfit` DECIMAL(38,18) NULL,
    `surplus_rese` DECIMAL(38,18) NULL,
    `special_rese` DECIMAL(38,18) NULL,
    `money_cap` DECIMAL(38,18) NULL,
    `trad_asset` DECIMAL(38,18) NULL,
    `notes_receiv` DECIMAL(38,18) NULL,
    `accounts_receiv` DECIMAL(38,18) NULL,
    `oth_receiv` DECIMAL(38,18) NULL,
    `prepayment` DECIMAL(38,18) NULL,
    `div_receiv` DECIMAL(38,18) NULL,
    `int_receiv` DECIMAL(38,18) NULL,
    `inventories` DECIMAL(38,18) NULL,
    `amor_exp` DECIMAL(38,18) NULL,
    `nca_within_1y` DECIMAL(38,18) NULL,
    `sett_rsrv` DECIMAL(38,18) NULL,
    `loanto_oth_bank_fi` DECIMAL(38,18) NULL,
    `premium_receiv` DECIMAL(38,18) NULL,
    `reinsur_receiv` DECIMAL(38,18) NULL,
    `reinsur_res_receiv` DECIMAL(38,18) NULL,
    `pur_resale_fa` DECIMAL(38,18) NULL,
    `oth_cur_assets` DECIMAL(38,18) NULL,
    `total_cur_assets` DECIMAL(38,18) NULL,
    `fa_avail_for_sale` DECIMAL(38,18) NULL,
    `htm_invest` DECIMAL(38,18) NULL,
    `lt_eqt_invest` DECIMAL(38,18) NULL,
    `invest_real_estate` DECIMAL(38,18) NULL,
    `time_deposits` DECIMAL(38,18) NULL,
    `oth_assets` DECIMAL(38,18) NULL,
    `lt_rec` DECIMAL(38,18) NULL,
    `fix_assets` DECIMAL(38,18) NULL,
    `cip` DECIMAL(38,18) NULL,
    `const_materials` DECIMAL(38,18) NULL,
    `fixed_assets_disp` DECIMAL(38,18) NULL,
    `produc_bio_assets` DECIMAL(38,18) NULL,
    `oil_and_gas_assets` DECIMAL(38,18) NULL,
    `intan_assets` DECIMAL(38,18) NULL,
    `r_and_d` DECIMAL(38,18) NULL,
    `goodwill` DECIMAL(38,18) NULL,
    `lt_amor_exp` DECIMAL(38,18) NULL,
    `defer_tax_assets` DECIMAL(38,18) NULL,
    `decr_in_disbur` DECIMAL(38,18) NULL,
    `oth_nca` DECIMAL(38,18) NULL,
    `total_nca` DECIMAL(38,18) NULL,
    `cash_reser_cb` DECIMAL(38,18) NULL,
    `depos_in_oth_bfi` DECIMAL(38,18) NULL,
    `prec_metals` DECIMAL(38,18) NULL,
    `deriv_assets` DECIMAL(38,18) NULL,
    `rr_reins_une_prem` DECIMAL(38,18) NULL,
    `rr_reins_outstd_cla` DECIMAL(38,18) NULL,
    `rr_reins_lins_liab` DECIMAL(38,18) NULL,
    `rr_reins_lthins_liab` DECIMAL(38,18) NULL,
    `refund_depos` DECIMAL(38,18) NULL,
    `ph_pledge_loans` DECIMAL(38,18) NULL,
    `refund_cap_depos` DECIMAL(38,18) NULL,
    `indep_acct_assets` DECIMAL(38,18) NULL,
    `client_depos` DECIMAL(38,18) NULL,
    `client_prov` DECIMAL(38,18) NULL,
    `transac_seat_fee` DECIMAL(38,18) NULL,
    `invest_as_receiv` DECIMAL(38,18) NULL,
    `total_assets` DECIMAL(38,18) NULL,
    `lt_borr` DECIMAL(38,18) NULL,
    `st_borr` DECIMAL(38,18) NULL,
    `cb_borr` DECIMAL(38,18) NULL,
    `depos_ib_deposits` DECIMAL(38,18) NULL,
    `loan_oth_bank` DECIMAL(38,18) NULL,
    `trading_fl` DECIMAL(38,18) NULL,
    `notes_payable` DECIMAL(38,18) NULL,
    `acct_payable` DECIMAL(38,18) NULL,
    `adv_receipts` DECIMAL(38,18) NULL,
    `sold_for_repur_fa` DECIMAL(38,18) NULL,
    `comm_payable` DECIMAL(38,18) NULL,
    `payroll_payable` DECIMAL(38,18) NULL,
    `taxes_payable` DECIMAL(38,18) NULL,
    `int_payable` DECIMAL(38,18) NULL,
    `div_payable` DECIMAL(38,18) NULL,
    `oth_payable` DECIMAL(38,18) NULL,
    `acc_exp` DECIMAL(38,18) NULL,
    `deferred_inc` DECIMAL(38,18) NULL,
    `st_bonds_payable` DECIMAL(38,18) NULL,
    `payable_to_reinsurer` DECIMAL(38,18) NULL,
    `rsrv_insur_cont` DECIMAL(38,18) NULL,
    `acting_trading_sec` DECIMAL(38,18) NULL,
    `acting_uw_sec` DECIMAL(38,18) NULL,
    `non_cur_liab_due_1y` DECIMAL(38,18) NULL,
    `oth_cur_liab` DECIMAL(38,18) NULL,
    `total_cur_liab` DECIMAL(38,18) NULL,
    `bond_payable` DECIMAL(38,18) NULL,
    `lt_payable` DECIMAL(38,18) NULL,
    `specific_payables` DECIMAL(38,18) NULL,
    `estimated_liab` DECIMAL(38,18) NULL,
    `defer_tax_liab` DECIMAL(38,18) NULL,
    `defer_inc_non_cur_liab` DECIMAL(38,18) NULL,
    `oth_ncl` DECIMAL(38,18) NULL,
    `total_ncl` DECIMAL(38,18) NULL,
    `depos_oth_bfi` DECIMAL(38,18) NULL,
    `deriv_liab` DECIMAL(38,18) NULL,
    `depos` DECIMAL(38,18) NULL,
    `agency_bus_liab` DECIMAL(38,18) NULL,
    `oth_liab` DECIMAL(38,18) NULL,
    `prem_receiv_adva` DECIMAL(38,18) NULL,
    `depos_received` DECIMAL(38,18) NULL,
    `ph_invest` DECIMAL(38,18) NULL,
    `reser_une_prem` DECIMAL(38,18) NULL,
    `reser_outstd_claims` DECIMAL(38,18) NULL,
    `reser_lins_liab` DECIMAL(38,18) NULL,
    `reser_lthins_liab` DECIMAL(38,18) NULL,
    `indept_acc_liab` DECIMAL(38,18) NULL,
    `pledge_borr` DECIMAL(38,18) NULL,
    `indem_payable` DECIMAL(38,18) NULL,
    `policy_div_payable` DECIMAL(38,18) NULL,
    `total_liab` DECIMAL(38,18) NULL,
    `treasury_share` DECIMAL(38,18) NULL,
    `ordin_risk_reser` DECIMAL(38,18) NULL,
    `forex_differ` DECIMAL(38,18) NULL,
    `invest_loss_unconf` DECIMAL(38,18) NULL,
    `minority_int` DECIMAL(38,18) NULL,
    `total_hldr_eqy_exc_min_int` DECIMAL(38,18) NULL,
    `total_hldr_eqy_inc_min_int` DECIMAL(38,18) NULL,
    `total_liab_hldr_eqy` DECIMAL(38,18) NULL,
    `lt_payroll_payable` DECIMAL(38,18) NULL,
    `oth_comp_income` DECIMAL(38,18) NULL,
    `oth_eqt_tools` DECIMAL(38,18) NULL,
    `oth_eqt_tools_p_shr` DECIMAL(38,18) NULL,
    `lending_funds` DECIMAL(38,18) NULL,
    `acc_receivable` DECIMAL(38,18) NULL,
    `st_fin_payable` DECIMAL(38,18) NULL,
    `payables` DECIMAL(38,18) NULL,
    `hfs_assets` DECIMAL(38,18) NULL,
    `hfs_sales` DECIMAL(38,18) NULL,
    `cost_fin_assets` DECIMAL(38,18) NULL,
    `fair_value_fin_assets` DECIMAL(38,18) NULL,
    `contract_assets` DECIMAL(38,18) NULL,
    `contract_liab` DECIMAL(38,18) NULL,
    `accounts_receiv_bill` DECIMAL(38,18) NULL,
    `accounts_pay` DECIMAL(38,18) NULL,
    `oth_rcv_total` DECIMAL(38,18) NULL,
    `fix_assets_total` DECIMAL(38,18) NULL,
    `cip_total` DECIMAL(38,18) NULL,
    `oth_pay_total` DECIMAL(38,18) NULL,
    `long_pay_total` DECIMAL(38,18) NULL,
    `debt_invest` DECIMAL(38,18) NULL,
    `oth_debt_invest` DECIMAL(38,18) NULL,
    `update_flag` VARCHAR(64) NULL,
    `source_plugin` VARCHAR(64) NOT NULL,
    `source_api` VARCHAR(64) NOT NULL,
    `ingested_at` DATETIME(3) NOT NULL,
    PRIMARY KEY (`ts_code`, `end_date`, `report_type`, `ann_date`),
    KEY `idx_balancesheet_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;

CREATE TABLE `tushare_pro__cashflow` (
    `ts_code` VARCHAR(64) NOT NULL,
    `ann_date` DATE NOT NULL,
    `f_ann_date` DATE NULL,
    `end_date` DATE NOT NULL,
    `comp_type` VARCHAR(64) NULL,
    `report_type` VARCHAR(64) NOT NULL,
    `end_type` VARCHAR(64) NULL,
    `net_profit` DECIMAL(38,18) NULL,
    `finan_exp` DECIMAL(38,18) NULL,
    `c_fr_sale_sg` DECIMAL(38,18) NULL,
    `recp_tax_rends` DECIMAL(38,18) NULL,
    `n_depos_incr_fi` DECIMAL(38,18) NULL,
    `n_incr_loans_cb` DECIMAL(38,18) NULL,
    `n_inc_borr_oth_fi` DECIMAL(38,18) NULL,
    `prem_fr_orig_contr` DECIMAL(38,18) NULL,
    `n_incr_insured_dep` DECIMAL(38,18) NULL,
    `n_reinsur_prem` DECIMAL(38,18) NULL,
    `n_incr_disp_tfa` DECIMAL(38,18) NULL,
    `ifc_cash_incr` DECIMAL(38,18) NULL,
    `n_incr_disp_faas` DECIMAL(38,18) NULL,
    `n_incr_loans_oth_bank` DECIMAL(38,18) NULL,
    `n_cap_incr_repur` DECIMAL(38,18) NULL,
    `c_fr_oth_operate_a` DECIMAL(38,18) NULL,
    `c_inf_fr_operate_a` DECIMAL(38,18) NULL,
    `c_paid_goods_s` DECIMAL(38,18) NULL,
    `c_paid_to_for_empl` DECIMAL(38,18) NULL,
    `c_paid_for_taxes` DECIMAL(38,18) NULL,
    `n_incr_clt_loan_adv` DECIMAL(38,18) NULL,
    `n_incr_dep_cbob` DECIMAL(38,18) NULL,
    `c_pay_claims_orig_inco` DECIMAL(38,18) NULL,
    `pay_handling_chrg` DECIMAL(38,18) NULL,
    `pay_comm_insur_plcy` DECIMAL(38,18) NULL,
    `oth_cash_pay_oper_act` DECIMAL(38,18) NULL,
    `st_cash_out_act` DECIMAL(38,18) NULL,
    `n_cashflow_act` DECIMAL(38,18) NULL,
    `oth_recp_ral_inv_act` DECIMAL(38,18) NULL,
    `c_disp_withdrwl_invest` DECIMAL(38,18) NULL,
    `c_recp_return_invest` DECIMAL(38,18) NULL,
    `n_recp_disp_fiolta` DECIMAL(38,18) NULL,
    `n_recp_disp_sobu` DECIMAL(38,18) NULL,
    `stot_inflows_inv_act` DECIMAL(38,18) NULL,
    `c_pay_acq_const_fiolta` DECIMAL(38,18) NULL,
    `c_paid_invest` DECIMAL(38,18) NULL,
    `n_disp_subs_oth_biz` DECIMAL(38,18) NULL,
    `oth_pay_ral_inv_act` DECIMAL(38,18) NULL,
    `n_incr_pledge_loan` DECIMAL(38,18) NULL,
    `stot_out_inv_act` DECIMAL(38,18) NULL,
    `n_cashflow_inv_act` DECIMAL(38,18) NULL,
    `c_recp_borrow` DECIMAL(38,18) NULL,
    `proc_issue_bonds` DECIMAL(38,18) NULL,
    `oth_cash_recp_ral_fnc_act` DECIMAL(38,18) NULL,
    `stot_cash_in_fnc_act` DECIMAL(38,18) NULL,
    `free_cashflow` DECIMAL(38,18) NULL,
    `c_prepay_amt_borr` DECIMAL(38,18) NULL,
    `c_pay_dist_dpcp_int_exp` DECIMAL(38,18) NULL,
    `incl_dvd_profit_paid_sc_ms` DECIMAL(38,18) NULL,
    `oth_cashpay_ral_fnc_act` DECIMAL(38,18) NULL,
    `stot_cashout_fnc_act` DECIMAL(38,18) NULL,
    `n_cash_flows_fnc_act` DECIMAL(38,18) NULL,
    `eff_fx_flu_cash` DECIMAL(38,18) NULL,
    `n_incr_cash_cash_equ` DECIMAL(38,18) NULL,
    `c_cash_equ_beg_period` DECIMAL(38,18) NULL,
    `c_cash_equ_end_period` DECIMAL(38,18) NULL,
    `c_recp_cap_contrib` DECIMAL(38,18) NULL,
    `incl_cash_rec_saims` DECIMAL(38,18) NULL,
    `uncon_invest_loss` DECIMAL(38,18) NULL,
    `prov_depr_assets` DECIMAL(38,18) NULL,
    `depr_fa_coga_dpba` DECIMAL(38,18) NULL,
    `amort_intang_assets` DECIMAL(38,18) NULL,
    `lt_amort_deferred_exp` DECIMAL(38,18) NULL,
    `decr_deferred_exp` DECIMAL(38,18) NULL,
    `incr_acc_exp` DECIMAL(38,18) NULL,
    `loss_disp_fiolta` DECIMAL(38,18) NULL,
    `loss_scr_fa` DECIMAL(38,18) NULL,
    `loss_fv_chg` DECIMAL(38,18) NULL,
    `invest_loss` DECIMAL(38,18) NULL,
    `decr_def_inc_tax_assets` DECIMAL(38,18) NULL,
    `incr_def_inc_tax_liab` DECIMAL(38,18) NULL,
    `decr_inventories` DECIMAL(38,18) NULL,
    `decr_oper_payable` DECIMAL(38,18) NULL,
    `incr_oper_payable` DECIMAL(38,18) NULL,
    `others` DECIMAL(38,18) NULL,
    `im_net_cashflow_oper_act` DECIMAL(38,18) NULL,
    `conv_debt_into_cap` DECIMAL(38,18) NULL,
    `conv_copbonds_due_within_1y` DECIMAL(38,18) NULL,
    `fa_fnc_leases` DECIMAL(38,18) NULL,
    `im_n_incr_cash_equ` DECIMAL(38,18) NULL,
    `net_dism_capital_add` DECIMAL(38,18) NULL,
    `net_cash_rece_sec` DECIMAL(38,18) NULL,
    `credit_impa_loss` DECIMAL(38,18) NULL,
    `use_right_asset_dep` DECIMAL(38,18) NULL,
    `oth_loss_asset` DECIMAL(38,18) NULL,
    `end_bal_cash` DECIMAL(38,18) NULL,
    `beg_bal_cash` DECIMAL(38,18) NULL,
    `end_bal_cash_equ` DECIMAL(38,18) NULL,
    `beg_bal_cash_equ` DECIMAL(38,18) NULL,
    `update_flag` VARCHAR(64) NULL,
    `source_plugin` VARCHAR(64) NOT NULL,
    `source_api` VARCHAR(64) NOT NULL,
    `ingested_at` DATETIME(3) NOT NULL,
    PRIMARY KEY (`ts_code`, `end_date`, `report_type`, `ann_date`),
    KEY `idx_cashflow_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;

CREATE TABLE `tushare_pro__fina_indicator` (
    `ts_code` VARCHAR(64) NOT NULL,
    `ann_date` DATE NOT NULL,
    `end_date` DATE NOT NULL,
    `eps` DECIMAL(38,18) NULL,
    `dt_eps` DECIMAL(38,18) NULL,
    `total_revenue_ps` DECIMAL(38,18) NULL,
    `revenue_ps` DECIMAL(38,18) NULL,
    `capital_rese_ps` DECIMAL(38,18) NULL,
    `surplus_rese_ps` DECIMAL(38,18) NULL,
    `undist_profit_ps` DECIMAL(38,18) NULL,
    `extra_item` DECIMAL(38,18) NULL,
    `profit_dedt` DECIMAL(38,18) NULL,
    `gross_margin` DECIMAL(38,18) NULL,
    `current_ratio` DECIMAL(38,18) NULL,
    `quick_ratio` DECIMAL(38,18) NULL,
    `cash_ratio` DECIMAL(38,18) NULL,
    `ar_turn` DECIMAL(38,18) NULL,
    `ca_turn` DECIMAL(38,18) NULL,
    `fa_turn` DECIMAL(38,18) NULL,
    `assets_turn` DECIMAL(38,18) NULL,
    `op_income` DECIMAL(38,18) NULL,
    `ebit` DECIMAL(38,18) NULL,
    `ebitda` DECIMAL(38,18) NULL,
    `fcff` DECIMAL(38,18) NULL,
    `fcfe` DECIMAL(38,18) NULL,
    `current_exint` DECIMAL(38,18) NULL,
    `noncurrent_exint` DECIMAL(38,18) NULL,
    `interestdebt` DECIMAL(38,18) NULL,
    `netdebt` DECIMAL(38,18) NULL,
    `tangible_asset` DECIMAL(38,18) NULL,
    `working_capital` DECIMAL(38,18) NULL,
    `networking_capital` DECIMAL(38,18) NULL,
    `invest_capital` DECIMAL(38,18) NULL,
    `retained_earnings` DECIMAL(38,18) NULL,
    `diluted2_eps` DECIMAL(38,18) NULL,
    `bps` DECIMAL(38,18) NULL,
    `ocfps` DECIMAL(38,18) NULL,
    `retainedps` DECIMAL(38,18) NULL,
    `cfps` DECIMAL(38,18) NULL,
    `ebit_ps` DECIMAL(38,18) NULL,
    `fcff_ps` DECIMAL(38,18) NULL,
    `fcfe_ps` DECIMAL(38,18) NULL,
    `netprofit_margin` DECIMAL(38,18) NULL,
    `grossprofit_margin` DECIMAL(38,18) NULL,
    `cogs_of_sales` DECIMAL(38,18) NULL,
    `expense_of_sales` DECIMAL(38,18) NULL,
    `profit_to_gr` DECIMAL(38,18) NULL,
    `saleexp_to_gr` DECIMAL(38,18) NULL,
    `adminexp_of_gr` DECIMAL(38,18) NULL,
    `finaexp_of_gr` DECIMAL(38,18) NULL,
    `impai_ttm` DECIMAL(38,18) NULL,
    `gc_of_gr` DECIMAL(38,18) NULL,
    `op_of_gr` DECIMAL(38,18) NULL,
    `ebit_of_gr` DECIMAL(38,18) NULL,
    `roe` DECIMAL(38,18) NULL,
    `roe_waa` DECIMAL(38,18) NULL,
    `roe_dt` DECIMAL(38,18) NULL,
    `roa` DECIMAL(38,18) NULL,
    `npta` DECIMAL(38,18) NULL,
    `roic` DECIMAL(38,18) NULL,
    `roe_yearly` DECIMAL(38,18) NULL,
    `roa2_yearly` DECIMAL(38,18) NULL,
    `debt_to_assets` DECIMAL(38,18) NULL,
    `assets_to_eqt` DECIMAL(38,18) NULL,
    `dp_assets_to_eqt` DECIMAL(38,18) NULL,
    `ca_to_assets` DECIMAL(38,18) NULL,
    `nca_to_assets` DECIMAL(38,18) NULL,
    `tbassets_to_totalassets` DECIMAL(38,18) NULL,
    `int_to_talcap` DECIMAL(38,18) NULL,
    `eqt_to_talcapital` DECIMAL(38,18) NULL,
    `currentdebt_to_debt` DECIMAL(38,18) NULL,
    `longdeb_to_debt` DECIMAL(38,18) NULL,
    `ocf_to_shortdebt` DECIMAL(38,18) NULL,
    `debt_to_eqt` DECIMAL(38,18) NULL,
    `eqt_to_debt` DECIMAL(38,18) NULL,
    `eqt_to_interestdebt` DECIMAL(38,18) NULL,
    `tangibleasset_to_debt` DECIMAL(38,18) NULL,
    `tangasset_to_intdebt` DECIMAL(38,18) NULL,
    `tangibleasset_to_netdebt` DECIMAL(38,18) NULL,
    `ocf_to_debt` DECIMAL(38,18) NULL,
    `turn_days` DECIMAL(38,18) NULL,
    `roa_yearly` DECIMAL(38,18) NULL,
    `roa_dp` DECIMAL(38,18) NULL,
    `fixed_assets` DECIMAL(38,18) NULL,
    `profit_to_op` DECIMAL(38,18) NULL,
    `q_saleexp_to_gr` DECIMAL(38,18) NULL,
    `q_gc_to_gr` DECIMAL(38,18) NULL,
    `q_roe` DECIMAL(38,18) NULL,
    `q_dt_roe` DECIMAL(38,18) NULL,
    `q_npta` DECIMAL(38,18) NULL,
    `q_ocf_to_sales` DECIMAL(38,18) NULL,
    `basic_eps_yoy` DECIMAL(38,18) NULL,
    `dt_eps_yoy` DECIMAL(38,18) NULL,
    `cfps_yoy` DECIMAL(38,18) NULL,
    `op_yoy` DECIMAL(38,18) NULL,
    `ebt_yoy` DECIMAL(38,18) NULL,
    `netprofit_yoy` DECIMAL(38,18) NULL,
    `dt_netprofit_yoy` DECIMAL(38,18) NULL,
    `ocf_yoy` DECIMAL(38,18) NULL,
    `roe_yoy` DECIMAL(38,18) NULL,
    `bps_yoy` DECIMAL(38,18) NULL,
    `assets_yoy` DECIMAL(38,18) NULL,
    `eqt_yoy` DECIMAL(38,18) NULL,
    `tr_yoy` DECIMAL(38,18) NULL,
    `or_yoy` DECIMAL(38,18) NULL,
    `q_sales_yoy` DECIMAL(38,18) NULL,
    `q_op_qoq` DECIMAL(38,18) NULL,
    `equity_yoy` DECIMAL(38,18) NULL,
    `source_plugin` VARCHAR(64) NOT NULL,
    `source_api` VARCHAR(64) NOT NULL,
    `ingested_at` DATETIME(3) NOT NULL,
    PRIMARY KEY (`ts_code`, `end_date`, `ann_date`),
    KEY `idx_fina_indicator_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;

CREATE TABLE `tushare_pro__fina_audit` (
    `ts_code` VARCHAR(64) NOT NULL,
    `ann_date` DATE NOT NULL,
    `end_date` DATE NOT NULL,
    `audit_result` VARCHAR(255) NULL,
    `audit_fees` DECIMAL(38,18) NULL,
    `audit_agency` VARCHAR(255) NULL,
    `audit_sign` VARCHAR(255) NULL,
    `source_plugin` VARCHAR(64) NOT NULL,
    `source_api` VARCHAR(64) NOT NULL,
    `ingested_at` DATETIME(3) NOT NULL,
    PRIMARY KEY (`ts_code`, `end_date`, `ann_date`),
    KEY `idx_fina_audit_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;

CREATE TABLE `tushare_pro__fina_mainbz` (
    `ts_code` VARCHAR(64) NOT NULL,
    `end_date` DATE NOT NULL,
    `bz_item` VARCHAR(255) NOT NULL,
    `bz_code` VARCHAR(64) NULL,
    `bz_sales` DECIMAL(38,18) NULL,
    `bz_profit` DECIMAL(38,18) NULL,
    `bz_cost` DECIMAL(38,18) NULL,
    `curr_type` VARCHAR(64) NOT NULL,
    `source_plugin` VARCHAR(64) NOT NULL,
    `source_api` VARCHAR(64) NOT NULL,
    `ingested_at` DATETIME(3) NOT NULL,
    PRIMARY KEY (`ts_code`, `end_date`, `bz_item`, `curr_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;

CREATE TABLE `tushare_pro__express` (
    `ts_code` VARCHAR(64) NOT NULL,
    `ann_date` DATE NOT NULL,
    `end_date` DATE NOT NULL,
    `revenue` DECIMAL(38,18) NULL,
    `operate_profit` DECIMAL(38,18) NULL,
    `total_profit` DECIMAL(38,18) NULL,
    `n_income` DECIMAL(38,18) NULL,
    `total_assets` DECIMAL(38,18) NULL,
    `total_hldr_eqy_exc_min_int` DECIMAL(38,18) NULL,
    `diluted_eps` DECIMAL(38,18) NULL,
    `diluted_roe` DECIMAL(38,18) NULL,
    `yoy_net_profit` DECIMAL(38,18) NULL,
    `bps` DECIMAL(38,18) NULL,
    `perf_summary` TEXT NULL,
    `update_flag` VARCHAR(64) NULL,
    `source_plugin` VARCHAR(64) NOT NULL,
    `source_api` VARCHAR(64) NOT NULL,
    `ingested_at` DATETIME(3) NOT NULL,
    PRIMARY KEY (`ts_code`, `end_date`, `ann_date`),
    KEY `idx_express_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;

CREATE TABLE `tushare_pro__forecast` (
    `ts_code` VARCHAR(64) NOT NULL,
    `ann_date` DATE NOT NULL,
    `end_date` DATE NOT NULL,
    `type` VARCHAR(64) NOT NULL,
    `p_change_min` DECIMAL(38,18) NULL,
    `p_change_max` DECIMAL(38,18) NULL,
    `net_profit_min` DECIMAL(38,18) NULL,
    `net_profit_max` DECIMAL(38,18) NULL,
    `last_parent_net` DECIMAL(38,18) NULL,
    `first_ann_date` DATE NULL,
    `summary` TEXT NULL,
    `change_reason` TEXT NULL,
    `update_flag` VARCHAR(64) NULL,
    `source_plugin` VARCHAR(64) NOT NULL,
    `source_api` VARCHAR(64) NOT NULL,
    `ingested_at` DATETIME(3) NOT NULL,
    PRIMARY KEY (`ts_code`, `end_date`, `ann_date`, `type`),
    KEY `idx_forecast_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;

CREATE TABLE `tushare_pro__disclosure_date` (
    `ts_code` VARCHAR(64) NOT NULL,
    `ann_date` DATE NULL,
    `end_date` DATE NOT NULL,
    `pre_date` DATE NULL,
    `actual_date` DATE NULL,
    `source_plugin` VARCHAR(64) NOT NULL,
    `source_api` VARCHAR(64) NOT NULL,
    `ingested_at` DATETIME(3) NOT NULL,
    PRIMARY KEY (`ts_code`, `end_date`),
    KEY `idx_disclosure_date_ann_date` (`ann_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;

